services:
  movie-app:
    build:
      context: .
      args:
        - VITE_API_KEY=375e4c38f90d2cee3287d6a60995f4da
        - VITE_IMG_URL=https://image.tmdb.org/t/p/w500
    ports:
      - "3000:3000"